In [14]:
%pip install sqlalchemy pymysql

Requirement already satisfied: sqlalchemy in c:\users\shifa\anaconda3\envs\data_analysis\lib\site-packages (2.1.3)
Requirement already satisfied: pymysql in c:\users\shifa\anaconda3\envs\data_analysis\lib\site-packages (1.2.3)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\shifa\anaconda3\envs\data_analysis\lib\site-packages (from sqlalchemy) (4.12.2)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [15]:
import pandas as pd
from sqlalchemy import create_engine

print("Imports successful!")

Imports successful!

In [16]:
password = "root1234"

engine = create_engine(
    f"mysql+pymysql://root:{password}@localhost:3306/fin_markets"
)

print("MySQL connection created!")

MySQL connection created!

In [17]:
import os

print(os.getcwd())

c:\Projects\Financial-markets-dashboard\notebooks

In [18]:
import os

print(os.listdir())

['01_download_data.ipynb', '02_cleaning.ipynb', '03_load_mysql.ipynb', '04_python_analysis.ipynb']

In [19]:
clean = pd.read_csv(r"C:\Projects\Financial-markets-dashboard\data\clean\prices_clean.csv")

print("Rows:", len(clean))
print("Columns:", list(clean.columns))
clean.head()

Rows: 10024
Columns: ['date', 'ticker', 'open', 'high', 'low', 'close', 'volume']

,date,ticker,open,high,low,close,volume
0,2021-10-01 04:00:00,AAPL,138.405160,139.400043,135.683881,139.136688,94639600
1,2021-10-04 04:00:00,AAPL,138.268556,138.707484,134.864521,135.713089,98322000
2,2021-10-05 04:00:00,AAPL,136.054517,138.736787,135.927714,137.634613,80861100
3,2021-10-06 04:00:00,AAPL,136.035028,138.649016,134.962114,138.502716,83221100
4,2021-10-07 04:00:00,AAPL,139.536579,140.668013,139.204956,139.760910,61732700

In [20]:
clean.head()

,date,ticker,open,high,low,close,volume
0,2021-10-01 04:00:00,AAPL,138.405160,139.400043,135.683881,139.136688,94639600
1,2021-10-04 04:00:00,AAPL,138.268556,138.707484,134.864521,135.713089,98322000
2,2021-10-05 04:00:00,AAPL,136.054517,138.736787,135.927714,137.634613,80861100
3,2021-10-06 04:00:00,AAPL,136.035028,138.649016,134.962114,138.502716,83221100
4,2021-10-07 04:00:00,AAPL,139.536579,140.668013,139.204956,139.760910,61732700

In [21]:
ids = pd.read_sql(
    "SELECT instrument_id, ticker FROM instruments",
    engine
)

ids

   instrument_id ticker
0              3   AAPL
1              8    AGG
2              6    GLD
3              5    JPM
4              4   MSFT
5              2    QQQ
6              1    SPY
7              7    TLT

In [22]:
prices = clean.merge(
    ids,
    on="ticker",
    how="left"
)

prices.head()

,date,ticker,open,high,low,close,volume,instrument_id
0,2021-10-01 04:00:00,AAPL,138.405160,139.400043,135.683881,139.136688,94639600,3
1,2021-10-04 04:00:00,AAPL,138.268556,138.707484,134.864521,135.713089,98322000,3
2,2021-10-05 04:00:00,AAPL,136.054517,138.736787,135.927714,137.634613,80861100,3
3,2021-10-06 04:00:00,AAPL,136.035028,138.649016,134.962114,138.502716,83221100,3
4,2021-10-07 04:00:00,AAPL,139.536579,140.668013,139.204956,139.760910,61732700,3

In [23]:
print("Total price rows:", len(prices))
print("Missing instrument IDs:", prices["instrument_id"].isna().sum())

Total price rows: 10024
Missing instrument IDs: 0

In [24]:
prices = prices.rename(columns={
    "date": "trade_date",
    "open": "open_price",
    "high": "high_price",
    "low": "low_price",
    "close": "close_price"
})

prices = prices[
    [
        "instrument_id",
        "trade_date",
        "open_price",
        "high_price",
        "low_price",
        "close_price",
        "volume"
    ]
]

prices.head()

,instrument_id,trade_date,open_price,high_price,low_price,close_price,volume
0,3,2021-10-01 04:00:00,138.405160,139.400043,135.683881,139.136688,94639600
1,3,2021-10-04 04:00:00,138.268556,138.707484,134.864521,135.713089,98322000
2,3,2021-10-05 04:00:00,136.054517,138.736787,135.927714,137.634613,80861100
3,3,2021-10-06 04:00:00,136.035028,138.649016,134.962114,138.502716,83221100
4,3,2021-10-07 04:00:00,139.536579,140.668013,139.204956,139.760910,61732700

In [26]:
print("Rows in prices:", len(prices))
print("Columns:", list(prices.columns))

prices.head()

Rows in prices: 10024
Columns: ['instrument_id', 'trade_date', 'open_price', 'high_price', 'low_price', 'close_price', 'volume']

,instrument_id,trade_date,open_price,high_price,low_price,close_price,volume
0,3,2021-10-01 04:00:00,138.405160,139.400043,135.683881,139.136688,94639600
1,3,2021-10-04 04:00:00,138.268556,138.707484,134.864521,135.713089,98322000
2,3,2021-10-05 04:00:00,136.054517,138.736787,135.927714,137.634613,80861100
3,3,2021-10-06 04:00:00,136.035028,138.649016,134.962114,138.502716,83221100
4,3,2021-10-07 04:00:00,139.536579,140.668013,139.204956,139.760910,61732700

In [27]:
from sqlalchemy import text

# Step 1: Check the number of rows already in MySQL
with engine.connect() as connection:
    db_count = connection.execute(
        text("SELECT COUNT(*) FROM fin_markets.daily_prices")
    ).scalar()

# Step 2: Compare the existing data with our DataFrame
print("Existing rows in MySQL:", db_count)
print("Rows in the DataFrame:", len(prices))

# Step 3: Avoid blindly inserting the same dataset again
if db_count == len(prices):
    print("Data already loaded. Skipping insertion.")
else:
    print("Row counts differ. Check the existing data before loading.")

Existing rows in MySQL: 10024
Rows in the DataFrame: 10024
Data already loaded. Skipping insertion.